version: "3.9"

services:
  web:
    build: .
    container_name: task_manager_web
    command: uv run gunicorn task_manager.wsgi --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    restart: unless-stopped
    volumes:
      - .:/app
    env_file:
      - .env
