sonar.projectKey=chustovalena_python-project-52
sonar.organization=chustovalena
sonar.sources=.
sonar.exclusions=**/migrations/**, **/tests/**, **/manage.py**, **/task_manager/wsgi.py**, **/task_manager/asgi.py**
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.version=3.13
