# Generated by Django 5.2.8 on 2025-11-25 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0001_initial'),
        ('task', '0003_alter_task_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='labels',
            field=models.ManyToManyField(related_name='tasks', to='label.label'),
        ),
    ]
