# Generated by Django 5.2.8 on 2025-11-26 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0001_initial'),
        ('task', '0004_task_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='labels',
            field=models.ManyToManyField(null=True, related_name='tasks', to='label.label'),
        ),
    ]
