# Generated by Django 5.2.8 on 2025-11-27 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0001_initial'),
        ('task', '0005_alter_task_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='labels',
            field=models.ManyToManyField(null=True, related_name='tasks', to='label.label', verbose_name='Метки'),
        ),
    ]
