# Generated by Django 5.2.8 on 2025-12-05 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0001_initial'),
        ('task', '0006_alter_task_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='labels',
            field=models.ManyToManyField(blank=True, null=True, related_name='tasks', to='label.label', verbose_name='Метки'),
        ),
    ]
