# Generated by Django 5.2.8 on 2025-12-10 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0002_alter_label_name'),
        ('task', '0009_alter_task_executor_alter_task_labels_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='label.label', verbose_name='Labels'),
        ),
    ]
